---
  - name: Checkout dehydrated
    git:
      repo: "https://github.com/lukas2511/dehydrated.git"
      dest: "/opt/dehydrated"
      version: master
      force: yes

  - name: create /etc/letsencrypt hierarchy
    file: dest=/etc/{{ item }}
          owner=dehydrated group=ssl-cert
          state=directory mode=0750
    with_items:
      - "letsencrypt"
      - "letsencrypt/live"
      - "letsencrypt/live/{{ domain }}"
      - "letsencrypt/renewal-hooks/"
      - "letsencrypt/renewal-hooks/post"

  - name: generate dehydrated folders
    file: dest=/etc/{{ item }}
          owner=dehydrated group=root
          state=directory
    with_items:
      - "dehydrated"

  - name: generate dehydrated hook.sh
    copy: dest=/etc/dehydrated/hook.sh
          src=dehydrated/hook.sh
          owner=dehydrated group=root mode=0775

  - name: generate dehydrated dns-01 private & key
    copy: dest=/etc/dehydrated/dns-01-key.{{ item }}
          content={{ lookup('keepass', 'ansible/ssl/dns-01/'+ansible_fqdn+'.attr_'+item) }}
          mode=0640 owner=dehydrated group=root
    with_items:
      - key
      - private


  - name: generate dehydrated config
    copy: dest=/etc/dehydrated/config
          src=dehydrated/config
          owner=dehydrated group=root mode=0664

  - name: ensure domain {{ domain }} is in domains.txt
    lineinfile: path=/etc/dehydrated/domains.txt
                state=present
                regexp='{{ domain }}'
                line='{{ domain }}'
                create=yes owner=root group=root mode=0664

  - name: create dehydrated user
    user: name=dehydrated group=ssl-cert state=present
    tags: install

  - name: generate or renew certificate (takes up to 5 seconds)
    shell: "/opt/dehydrated/dehydrated --cron"

#  - name: generate dehydrated systemd.timer
